// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfydugoedxcjmrqyanzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmeWR1Z29lZHhjam1ycXlhbnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzUwNzEsImV4cCI6MjA2NTcxMTA3MX0.o7LqLfH00aYcg7Tm-9z4xJnAEGmV-fX5j0R9oRCON6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);